---
development:
  cloud_name: dmaqxrmgs
  api_key: '666537135232723'
  api_secret: CnIAZyfUmb2q8r6dAjs9tAZeWSk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dmaqxrmgs
  api_key: '666537135232723'
  api_secret: CnIAZyfUmb2q8r6dAjs9tAZeWSk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dmaqxrmgs
  api_key: '666537135232723'
  api_secret: CnIAZyfUmb2q8r6dAjs9tAZeWSk
  enhance_image_tag: true
  static_image_support: false
